import { NextPage } from 'next';
import Head from 'next/head';

import tw from 'twin.macro';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>NextJS - TypeScript - Tailwind - Styled Components - Twin.Macro</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HelloFromTW>Hello From TW</HelloFromTW>
        </div>
    );
};

export default Home;

const HelloFromTW = tw.h1`
    font-size[xx-large]
`;
