import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import AddExpense from "../components/AddExpense";
import Expenses from "../components/Expenses";

interface ExpenseType {
  title: string;
  cost: string;
}

const Home: NextPage = () => {
  const [expenses, setExpenses] = useState<ExpenseType[] | []>([]);

  console.log(expenses);

  return (
    <div>
      <Head>
        <title>Budget Planning App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddExpense expenses={expenses} setExpenses={setExpenses} />
      <Expenses expenses={expenses} />
    </div>
  );
};

export default Home;
