import { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';
import styled from 'styled-components';
import tw from 'twin.macro';
import AddBudgetModal from '../components/AddBudgetModal';
import BudgetCard from '../components/BudgetCard';

const Home: NextPage = () => {
	const [modalOpen, setModalOpen] = useState(false);
	const budgetButtonRef = useRef<HTMLButtonElement>(null);

	return (
		<Container>
			<Head>
				<title>Budget Planning App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeaderWrapper>
				<HeaderTitle>Budgets</HeaderTitle>
				<Button ref={budgetButtonRef} primary={true}>
					Add Budget
				</Button>
				<Button onClick={() => setModalOpen(true)} primary={false}>
					Add Expense
				</Button>
			</HeaderWrapper>
			<GridDiv>
				<BudgetCard name="Entertainment" amount={200} max={1000} />
				<BudgetCard name="Food" amount={200} max={400} />
			</GridDiv>
			<AddBudgetModal
				modalOpen={modalOpen}
				setModalOpen={setModalOpen}
				budgetButtonRef={budgetButtonRef}
			/>
		</Container>
	);
};

export default Home;

const Container = tw.div`
	mx-3
	my-6
`;

const HeaderWrapper = tw.div`
	flex
	mb-4
	gap-2
	align-items[center]
`;

const HeaderTitle = tw.h1`
	font-size[xx-large]
	font-bold
	mr-auto
`;

type ButtonProps = {
	primary: boolean;
};

const Button = styled.button(({ primary }: ButtonProps) => [
	primary
		? tw`
		background-color[#b840f0]
		text-white
	`
		: tw`
		text-[#b840f0]
		hover:text-white
	`,

	tw`
		border-radius[4px]
		border-2
		border-color[#b840f0]
		px-2
		py-1
		font-medium
    transition[all 0.3s ease-in-out]
	
		hover:background-color[#623875]
		hover:border-color[#623875]
	`,
]);

const GridDiv = tw.div`
	grid
	grid-template-columns[repeat(auto-fill, minmax(300px, 1fr))]
	gap-4
	align-items[flex-start]
`;
